### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (200,18,4) (100,1,1)

### ISSUE THREAD

**Issue by yomamdde** [ibaiGorordo/TfLite-Ultra-Fast-Lane-Detection-Inference#4]
I encountered an error while running the lane detection script.

`2023-07-13 16:38:19.233089: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/nvidia/Downloads/TfLite-Ultra-Fast-Lane-Detection-Inference/videoLaneDetection.py", line 32, in <module>
    output_img = lane_detector.detect_lanes(frame)
  File "/home/nvidia/Downloads/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 79, in detect_lanes
    self.lanes_points, self.lanes_detected = self.process_output(output, self.cfg)
  File "/home/nvidia/Downloads/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 135, in process_output
    loc = np.sum(prob * idx, axis=0)
ValueError: operands could not be broadcast together with shapes (200,18,4) (100,1,1)`

It would be really helpful if you could look into this issue and recommend a solution.

**Comment by yomamdde** [comment]
I solved it. I downloaded the wrong model(tusimple-> culane).
