### ISSUE TITLE
Issue when running example as suggested

### ISSUE THREAD

**Issue by Ben-schlch** [ibaiGorordo/TfLite-Ultra-Fast-Lane-Detection-Inference#5]
Running interference on single picture with model from repository results in following error:

python imageLaneDetection.py

Traceback (most recent call last):
  File "imageLaneDetection.py", line 20, in <module>
    output_img = lane_detector.detect_lanes(img)
  File "/home/rollerz/Documents/Vorgänger/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 79, in detect_lanes
    self.lanes_points, self.lanes_detected = self.process_output(output, self.cfg)
  File "/home/rollerz/Documents/Vorgänger/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 163, in process_output
    return np.array(lane_points_mat), np.array(lanes_detected)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

**Comment by Ben-schlch** [comment]
Numpy version issue:

numpy==1.23.5 works fine. Please adjust requirements.txt
